
export const TASK_API_REQUEST                 = 'TASK_API_REQUEST';
export const TASK_FORM_INVALID                = 'TASK_FORM_INVALID';
export const TASK_ALERT_RUNTIME_ERROR         = 'TASK_ALERT_RUNTIME_ERROR';
export const TASK_ALERT_SESSION_ERROR         = 'TASK_ALERT_SESSION_ERROR';
export const TASK_ALERT_REQUEST_ERROR         = 'TASK_ALERT_REQUEST_ERROR';
export const TASK_ALERT_CONNECTION_ERROR      = 'TASK_ALERT_CONNECTION_ERROR';
export const TASK_ALERT_SERVERINTERNAL_ERROR  = 'TASK_ALERT_SERVERINTERNAL_ERROR';